### ISSUE TITLE
Ello Mah Good Sir

### ISSUE THREAD

**Issue by ghost** [kartik007007/Tunein.com-GiftCard-Generator#1]
If you want to keep its obfuscated so nobody can see the code!

 you need to remove your first commit because it shows all your code unobfuscated!

While your at it also please remove the Hit logger ( learn how to hide it even with "obfuscated" its obvious in about 2 seconds because the call to IP)

**Comment by Hail2Hydra** [comment]
also please remove the Hitlogger :/

**Comment by Hail2Hydra** [comment]
Thank You Very Much -_-

**Comment by Kittu-xD** [comment]
> Hey! Thanks for letting me know!

**But i guess there's no need to obfuscate as it's kinda straight forward code '-'**
